name: 'Setup SwiftWasm'
description: 'Download a SwiftWasm toolchain and add it to the PATH'
branding:
  color: orange
  icon: download
inputs:
  swift-version:
    description: 'Swift version to configure. Reads from .swift-version if unset. Use default value if both are absent.'
runs:
  using: 'node16'
  main: 'dist/index.js'
