name: 'Setup SwiftWasm'
description: 'Download a SwiftWasm toolchain and add it to the PATH'
branding:
  color: orange
  icon: download
inputs:
  swift-version:
    description: 'Swift version to configure. Reads from .swift-version if unset. Use default value if both are absent.'
  add-to-path:
    description: 'Add the toolchain to the PATH'
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
