name: 'Setup Nightly SwiftWasm'
description: 'Download a latest nightly SwiftWasm toolchain and add it to the PATH'
branding:
  color: orange
  icon: download
inputs:
  token:
    description: Personal access token (PAT) used to fetch releases.
    default: ${{ github.token }}
  add-to-path:
    description: 'Add the toolchain to the PATH'
    default: 'true'
runs:
  using: 'node16'
  main: '../dist/nightly/index.js'
