name: "Install Swift toolchain"
description: "Download and install a Swift toolchain from a tarball URL on Linux runners."
inputs:
  download-url:
    description: "Direct URL to the Swift toolchain tarball."
    required: true
runs:
  using: "composite"
  steps:
    - name: Download toolchain archive
      shell: bash
      run: |
        set -euo pipefail
        url="${{ inputs.download-url }}"
        workdir="$(mktemp -d)"
        echo "Downloading Swift toolchain from $url"
        curl -L "$url" -o "$workdir/swift.tar.gz"
        echo "Archive downloaded to $workdir/swift.tar.gz"
        echo "workdir=$workdir" >> "$GITHUB_OUTPUT"
      id: download

    - name: Install toolchain
      shell: bash
      run: |
        set -euo pipefail
        archive_dir="${{ steps.download.outputs.workdir }}"
        archive="$archive_dir/swift.tar.gz"
        install_root="/opt/swift"
        echo "Installing Swift toolchain into $install_root"
        sudo rm -rf "$install_root"
        sudo mkdir -p "$install_root"
        sudo tar -xzf "$archive" -C "$install_root" --strip-components=1
        echo "$install_root/usr/bin" >> "$GITHUB_PATH"
        echo "Swift installed; version:"
        swift --version
